# Generated by Django 6.0.7 on 2026-07-29 18:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Согласие на обработку персональных данных', max_length=200, verbose_name='Название')),
                ('file', models.FileField(upload_to='consents/', verbose_name='PDF файл')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Процедура')),
                ('image', models.FileField(blank=True, null=True, upload_to='procedures/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Фото услуги')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Длительность (мин)')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая цена')),
            ],
            options={
                'verbose_name': 'Процедура',
                'verbose_name_plural': 'Процедуры',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Промокод')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
                ('discount_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка, %')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Действует с')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Действует по')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('image', models.FileField(blank=True, null=True, upload_to='salons/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Фото салона')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон салона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Салон',
                'verbose_name_plural': 'Салоны',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон менеджера')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='ConsentAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +79998887766 (10–15 цифр).', regex='^\\+?\\d{10,15}$')], verbose_name='Телефон')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, verbose_name='Принято')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consents', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='core.consentdocument')),
            ],
            options={
                'verbose_name': 'Принятие согласия',
                'verbose_name_plural': 'Принятия согласия',
                'ordering': ['-accepted_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +79998887766 (10–15 цифр).', regex='^\\+?\\d{10,15}$')], verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль клиента',
                'verbose_name_plural': 'Профили клиентов',
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('photo', models.FileField(blank=True, null=True, upload_to='specialists/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Фото мастера')),
                ('bio', models.TextField(blank=True, verbose_name='Специальность')),
                ('experience', models.TextField(blank=True, verbose_name='Стаж работы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('procedures', models.ManyToManyField(blank=True, related_name='specialists', to='core.procedure', verbose_name='Какие услуги делает')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в салоне')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='core.procedure')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='core.salon')),
            ],
            options={
                'verbose_name': 'Процедура в салоне',
                'verbose_name_plural': 'Процедуры в салонах',
                'constraints': [models.UniqueConstraint(fields=('salon', 'procedure'), name='uniq_salon_procedure')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=120, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +79998887766 (10–15 цифр).', regex='^\\+?\\d{10,15}$')], verbose_name='Телефон')),
                ('question', models.CharField(blank=True, max_length=300, null=True, verbose_name='Вопрос')),
                ('start_at', models.DateTimeField(verbose_name='Начало')),
                ('end_at', models.DateTimeField(verbose_name='Конец')),
                ('price_original', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена без скидки')),
                ('price_final', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена со скидкой')),
                ('source', models.CharField(choices=[('web', 'Сайт'), ('phone', 'Звонок')], default='web', max_length=10, verbose_name='Источник')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтверждена'), ('canceled', 'Отменена')], default='new', max_length=12, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('payment_id', models.CharField(blank=True, max_length=100, verbose_name='ID платежа')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.procedure')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promocode')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.salon')),
                ('specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.specialist')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-start_at'],
                'indexes': [models.Index(fields=['salon', 'start_at'], name='core_bookin_salon_i_5c89aa_idx'), models.Index(fields=['specialist', 'start_at'], name='core_bookin_special_bcecf0_idx'), models.Index(fields=['phone', 'start_at'], name='core_bookin_phone_e7c933_idx')],
            },
        ),
        migrations.CreateModel(
            name='SpecialistSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialists', to='core.salon')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salons', to='core.specialist')),
            ],
            options={
                'verbose_name': 'Специалист в салоне',
                'verbose_name_plural': 'Специалисты в салонах',
                'constraints': [models.UniqueConstraint(fields=('specialist', 'salon'), name='uniq_specialist_salon')],
            },
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='С')),
                ('end_time', models.TimeField(verbose_name='До')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='core.salon')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='core.specialist')),
            ],
            options={
                'verbose_name': 'Смена специалиста',
                'verbose_name_plural': 'Смены специалистов',
                'ordering': ['-date', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('salon', 'specialist', 'date', 'start_time', 'end_time'), name='uniq_shift_exact')],
            },
        ),
    ]
