# Generated by Django 6.0.7 on 2026-08-02 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +79998887766 (10–15 цифр).', regex='^\\+?\\d{10,15}$')], verbose_name='Телефон')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Заявка на звонок',
                'verbose_name_plural': 'Заявки на звонок',
                'ordering': ['-created_at'],
            },
        ),
    ]
